requirement_analysis_task:
  description: >
    用户需求为：{content}
    分析用户提出的功能需求，梳理核心诉求与场景。需评估需求的必要性、可行性与优先级，
    识别潜在的用户痛点与商业价值，同时考虑技术实现难度与资源投入。
    需结合市场同类产品情况，提出差异化建议，并形成结构化的需求分析报告。
  expected_output: >
    一份详细的需求分析报告，包含需求概述、用户场景分析、功能拆解、优先级评估、
    技术可行性分析、商业价值评估及建议方案。所有内容需用中文撰写。
  agent: product_manager

  architecture_design_task:
  description: >
    根据需求分析报告进行系统架构设计，确定技术栈选型、架构模式与整体框架。
    需进行组件划分、模块接口设计、数据流转规划，同时考虑系统可扩展性、
    安全性、性能与可维护性。需评估技术方案的可行性，提供架构图与关键技术说明。
  expected_output: >
    一份完整的架构设计报告，包含架构概述、技术栈选型说明、系统组件结构图、
    模块接口定义、数据流程图、非功能需求实现方案及技术风险评估。
    所有内容需用中文撰写。
  agent: software_architect

php_fullstack_development_task:
  description: >
    根据架构设计报告完成PHP全栈开发工作。需实现前端页面与交互逻辑、
    后端API接口开发、数据库表结构与查询优化，
    确保前后端数据交互顺畅。需遵循代码规范进行单元测试与集成测试，修复开发中发现的问题，
    并编写开发说明文档。
  expected_output: >
    一份包含完整开发成果的交付报告，内容包括：功能实现清单、核心代码说明（关键模块逻辑）、
    数据库脚本、测试用例与结果、部署步骤。所有内容需用中文撰写。
  agent: php_fullstack_developer